
server:
    port: 8080
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/banGao
        username: root
        password: khanh123
    jpa:
        hibernate:
            ddl-auto: update
            naming:
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl